ALTER TABLE tran_dau 
ADD COLUMN IF NOT EXISTS current_period VARCHAR(20) DEFAULT 'HALF_1',
ADD COLUMN IF NOT EXISTS half1_start_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS half1_end_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS half2_start_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS half2_end_time TIMESTAMP WITH TIME ZONE;
