export const desktopStyles = {
  wrapper: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row' as const,
    width: '100%',
    maxWidth: '100%',
    gap: '12px',
    padding: '12px 24px',
    boxSizing: 'border-box' as const,
    background: 'var(--color-bg, #f8fafc)',
    position: 'relative' as const,
    fontFamily: "'Hanken Grotesk', 'Inter', sans-serif",
  },
  backBtn: {
    position: 'absolute' as const,
    top: '16px',
    left: '24px',
    color: 'var(--color-text-muted, #94a3b8)',
    fontSize: '14px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    transition: 'color 0.2s',
  },
  columnHomeAway: {
    display: 'flex',
    flexDirection: 'column' as const,
    flex: '0 0 28%',
    boxSizing: 'border-box' as const,
  },
  columnCenter: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
    flex: '1 1 auto',
    boxSizing: 'border-box' as const,
    minWidth: 0,
  },
  card: {
    display: 'flex',
    flexDirection: 'column' as const,
    background: 'var(--color-surface, #ffffff)',
    padding: '24px',
    borderRadius: '8px',
    boxShadow: 'var(--shadow-sm, 0 1px 2px rgba(0, 0, 0, 0.05))',
    border: '1px solid var(--color-border-light, #f1f5f9)',
    boxSizing: 'border-box' as const,
  },
  cardTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: 'var(--color-primary, #0F766E)',
    marginBottom: '24px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    textAlign: 'center' as const,
  },
  lineupSectionTitle: {
    fontSize: '11px',
    color: 'var(--color-text-muted, #94a3b8)',
    fontWeight: 600,
    marginBottom: '12px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  startersGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
    marginBottom: '24px',
  },
  benchGrid: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
  },
  playerButton: (isPopoverOpen: boolean, isRedCarded: boolean) => ({
    display: 'flex',
    alignItems: 'flex-start' as const,
    gap: '6px',
    padding: '6px 8px',
    width: '100%',
    background: 'rgba(255,255,255,0.04)',
    border: isPopoverOpen ? '2px solid var(--color-primary, #0F766E)' : '1px solid rgba(255, 255, 255, 0.08)',
    color: '#cbd5e1',
    borderRadius: '7px',
    cursor: isRedCarded ? 'not-allowed' : 'pointer',
    opacity: isRedCarded ? 0.5 : 1,
    textDecoration: isRedCarded ? 'line-through' : 'none',
    boxSizing: 'border-box' as const,
    boxShadow: isPopoverOpen ? '0 0 0 3px rgba(15, 118, 110, 0.15)' : 'none',
    transition: 'all 0.15s ease-in-out',
    marginBottom: '4px',
  }),
  benchPlayerBox: {
    display: 'flex',
    alignItems: 'flex-start' as const,
    gap: '6px',
    padding: '6px 8px',
    width: '100%',
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '7px',
    opacity: 0.8,
    boxSizing: 'border-box' as const,
    marginBottom: '4px',
  },
  popover: (isHome: boolean) => ({
    position: 'absolute' as const,
    zIndex: 50,
    top: 0,
    ...(isHome ? { left: '105%' } : { right: '105%' }),
    width: '160px',
    background: 'var(--color-surface, #ffffff)',
    boxShadow: 'var(--shadow-lg, 0 10px 15px -3px rgba(0, 0, 0, 0.1))',
    borderRadius: '8px',
    border: '1px solid var(--color-border-light, #f1f5f9)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  }),
  popoverActionBtn: (bgColor: string, hoverColor: string) => ({
    width: '100%',
    padding: '10px 12px',
    background: bgColor,
    color: '#ffffff',
    fontSize: '11px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    border: 'none',
    cursor: 'pointer',
    transition: 'background 0.15s',
  }),
  scoreboardCard: {
    background: 'var(--color-surface, #ffffff)',
    padding: '32px',
    borderRadius: '8px',
    boxShadow: 'var(--shadow-sm, 0 1px 2px rgba(0, 0, 0, 0.05))',
    border: '1px solid var(--color-border-light, #f1f5f9)',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    boxSizing: 'border-box' as const,
  },
  roundHeader: {
    fontSize: '14px',
    fontWeight: 700,
    color: 'var(--color-text-secondary, #334155)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  timerText: (isLive: boolean) => ({
    fontWeight: 700,
    fontSize: '18px',
    marginBottom: '32px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: isLive ? 'var(--color-live, #EF4444)' : 'var(--color-text, #334155)',
  }),
  scoreboardTeamsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '40px',
    width: '100%',
    marginBottom: '24px',
  },
  scoreboardTeamCode: (align: 'left' | 'right') => ({
    fontSize: '36px',
    fontWeight: 300,
    color: 'var(--color-text-heading, #0F172A)',
    flex: 1,
    textAlign: align,
  }),
  scoreboardBigScore: {
    fontSize: '60px',
    fontWeight: 400,
    color: 'var(--color-text-heading, #0F172A)',
    flexShrink: 0,
    letterSpacing: '-2px',
  },
  goalScorersRow: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-between',
    fontSize: '11px',
    color: 'var(--color-text-muted, #94a3b8)',
    marginBottom: '40px',
    paddingLeft: '48px',
    paddingRight: '48px',
    boxSizing: 'border-box' as const,
  },
  scorersColumn: (align: 'left' | 'right') => ({
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    textAlign: align,
    flex: 1,
    alignItems: align === 'left' ? 'flex-start' : 'flex-end',
    ...(align === 'left' ? { paddingLeft: '32px' } : { paddingRight: '32px' }),
  }),
  ctaRow: {
    width: '100%',
    display: 'flex',
    gap: '12px',
  },
  ctaButton: (bgColor: string, flexValue: number = 1) => ({
    flex: flexValue,
    background: bgColor,
    color: '#ffffff',
    fontWeight: 600,
    padding: '12px 16px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '8px',
    borderRadius: '4px',
    border: 'none',
    cursor: 'pointer',
    transition: 'background 0.15s',
    fontSize: '13px',
  }),
  timelineCard: {
    background: 'var(--color-surface, #ffffff)',
    padding: '24px',
    borderRadius: '8px',
    boxShadow: 'var(--shadow-sm, 0 1px 2px rgba(0, 0, 0, 0.05))',
    border: '1px solid var(--color-border-light, #f1f5f9)',
    display: 'flex',
    flexDirection: 'column' as const,
    boxSizing: 'border-box' as const,
  },
  timelineHeader: {
    fontSize: '14px',
    fontWeight: 700,
    color: 'var(--color-text-secondary, #334155)',
    textTransform: 'uppercase' as const,
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    paddingBottom: '12px',
    borderBottom: '1px solid var(--color-border-light, #f1f5f9)',
  },
  timelineList: {
    flex: 1,
    overflowY: 'auto' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  timelineRow: {
    fontSize: '13px',
    color: 'var(--color-text, #334155)',
    fontWeight: 500,
    padding: '6px 0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid var(--color-border-light, #f1f5f9)',
  },
  timelineText: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  timelineDeleteBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--color-text-muted, #94a3b8)',
    cursor: 'pointer',
    padding: '0 8px',
    fontSize: '14px',
    transition: 'color 0.15s',
  }
};
export const mobileStyles = desktopStyles;
